version: '3.5'
services:
  gitlab:
      image: 'gitlab/gitlab-ce:11.10.4-ce.0'
      container_name: 'gitlab'
      restart: always
      hostname: 'gitlab.com'
      ports:
        - '80:80'
        - '22:22'
      volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
